// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: stats.proto

package main

import (
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          string                 `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *Attribute) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type PostStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         int32                  `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Views         int32                  `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Comments      int32                  `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStat) Reset() {
	*x = PostStat{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStat) ProtoMessage() {}

func (x *PostStat) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStat.ProtoReflect.Descriptor instead.
func (*PostStat) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *PostStat) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostStat) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PostStat) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type ViewsDynamic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []int32                `protobuf:"varint,1,rep,packed,name=views,proto3" json:"views,omitempty"`
	Times         []*timestamp.Timestamp `protobuf:"bytes,2,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewsDynamic) Reset() {
	*x = ViewsDynamic{}
	mi := &file_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewsDynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsDynamic) ProtoMessage() {}

func (x *ViewsDynamic) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsDynamic.ProtoReflect.Descriptor instead.
func (*ViewsDynamic) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *ViewsDynamic) GetViews() []int32 {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *ViewsDynamic) GetTimes() []*timestamp.Timestamp {
	if x != nil {
		return x.Times
	}
	return nil
}

type LikesDynamic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         []int32                `protobuf:"varint,1,rep,packed,name=likes,proto3" json:"likes,omitempty"`
	Times         []*timestamp.Timestamp `protobuf:"bytes,2,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikesDynamic) Reset() {
	*x = LikesDynamic{}
	mi := &file_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikesDynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikesDynamic) ProtoMessage() {}

func (x *LikesDynamic) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikesDynamic.ProtoReflect.Descriptor instead.
func (*LikesDynamic) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *LikesDynamic) GetLikes() []int32 {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *LikesDynamic) GetTimes() []*timestamp.Timestamp {
	if x != nil {
		return x.Times
	}
	return nil
}

type CommentsDynamic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []int32                `protobuf:"varint,1,rep,packed,name=comments,proto3" json:"comments,omitempty"`
	Times         []*timestamp.Timestamp `protobuf:"bytes,2,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsDynamic) Reset() {
	*x = CommentsDynamic{}
	mi := &file_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsDynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsDynamic) ProtoMessage() {}

func (x *CommentsDynamic) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsDynamic.ProtoReflect.Descriptor instead.
func (*CommentsDynamic) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *CommentsDynamic) GetComments() []int32 {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentsDynamic) GetTimes() []*timestamp.Timestamp {
	if x != nil {
		return x.Times
	}
	return nil
}

type TopPosts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []string               `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPosts) Reset() {
	*x = TopPosts{}
	mi := &file_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPosts) ProtoMessage() {}

func (x *TopPosts) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPosts.ProtoReflect.Descriptor instead.
func (*TopPosts) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TopPosts) GetPosts() []string {
	if x != nil {
		return x.Posts
	}
	return nil
}

type TopUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsers) Reset() {
	*x = TopUsers{}
	mi := &file_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsers) ProtoMessage() {}

func (x *TopUsers) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsers.ProtoReflect.Descriptor instead.
func (*TopUsers) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopUsers) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05stats\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\vPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"\x1f\n" +
	"\tAttribute\x12\x12\n" +
	"\x04attr\x18\x01 \x01(\tR\x04attr\"R\n" +
	"\bPostStat\x12\x14\n" +
	"\x05likes\x18\x01 \x01(\x05R\x05likes\x12\x14\n" +
	"\x05views\x18\x02 \x01(\x05R\x05views\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\x05R\bcomments\"V\n" +
	"\fViewsDynamic\x12\x14\n" +
	"\x05views\x18\x01 \x03(\x05R\x05views\x120\n" +
	"\x05times\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\x05times\"V\n" +
	"\fLikesDynamic\x12\x14\n" +
	"\x05likes\x18\x01 \x03(\x05R\x05likes\x120\n" +
	"\x05times\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\x05times\"_\n" +
	"\x0fCommentsDynamic\x12\x1a\n" +
	"\bcomments\x18\x01 \x03(\x05R\bcomments\x120\n" +
	"\x05times\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\x05times\" \n" +
	"\bTopPosts\x12\x14\n" +
	"\x05posts\x18\x01 \x03(\tR\x05posts\" \n" +
	"\bTopUsers\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users2\xf5\x03\n" +
	"\x05Stats\x12G\n" +
	"\vGetPostStat\x12\x12.stats.PostRequest\x1a\x0f.stats.PostStat\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/stats/post\x12T\n" +
	"\x0eGetViesDynamic\x12\x12.stats.PostRequest\x1a\x13.stats.ViewsDynamic\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stats/post/views\x12U\n" +
	"\x0fGetLikesDynamic\x12\x12.stats.PostRequest\x1a\x13.stats.LikesDynamic\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stats/post/likes\x12^\n" +
	"\x12GetCommentsDynamic\x12\x12.stats.PostRequest\x1a\x16.stats.CommentsDynamic\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/stats/post/comments\x12J\n" +
	"\vGetTopPosts\x12\x10.stats.Attribute\x1a\x0f.stats.TopPosts\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/stats/top-posts\x12J\n" +
	"\vGetTopUsers\x12\x10.stats.Attribute\x1a\x0f.stats.TopUsers\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/stats/top-usersB0Z.github.com/ttser1085/Social-Network/stats/mainb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stats_proto_goTypes = []any{
	(*PostRequest)(nil),         // 0: stats.PostRequest
	(*Attribute)(nil),           // 1: stats.Attribute
	(*PostStat)(nil),            // 2: stats.PostStat
	(*ViewsDynamic)(nil),        // 3: stats.ViewsDynamic
	(*LikesDynamic)(nil),        // 4: stats.LikesDynamic
	(*CommentsDynamic)(nil),     // 5: stats.CommentsDynamic
	(*TopPosts)(nil),            // 6: stats.TopPosts
	(*TopUsers)(nil),            // 7: stats.TopUsers
	(*timestamp.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_stats_proto_depIdxs = []int32{
	8, // 0: stats.ViewsDynamic.times:type_name -> google.protobuf.Timestamp
	8, // 1: stats.LikesDynamic.times:type_name -> google.protobuf.Timestamp
	8, // 2: stats.CommentsDynamic.times:type_name -> google.protobuf.Timestamp
	0, // 3: stats.Stats.GetPostStat:input_type -> stats.PostRequest
	0, // 4: stats.Stats.GetViesDynamic:input_type -> stats.PostRequest
	0, // 5: stats.Stats.GetLikesDynamic:input_type -> stats.PostRequest
	0, // 6: stats.Stats.GetCommentsDynamic:input_type -> stats.PostRequest
	1, // 7: stats.Stats.GetTopPosts:input_type -> stats.Attribute
	1, // 8: stats.Stats.GetTopUsers:input_type -> stats.Attribute
	2, // 9: stats.Stats.GetPostStat:output_type -> stats.PostStat
	3, // 10: stats.Stats.GetViesDynamic:output_type -> stats.ViewsDynamic
	4, // 11: stats.Stats.GetLikesDynamic:output_type -> stats.LikesDynamic
	5, // 12: stats.Stats.GetCommentsDynamic:output_type -> stats.CommentsDynamic
	6, // 13: stats.Stats.GetTopPosts:output_type -> stats.TopPosts
	7, // 14: stats.Stats.GetTopUsers:output_type -> stats.TopUsers
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
