// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: stats.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stats_GetPostStat_FullMethodName        = "/stats.Stats/GetPostStat"
	Stats_GetViesDynamic_FullMethodName     = "/stats.Stats/GetViesDynamic"
	Stats_GetLikesDynamic_FullMethodName    = "/stats.Stats/GetLikesDynamic"
	Stats_GetCommentsDynamic_FullMethodName = "/stats.Stats/GetCommentsDynamic"
	Stats_GetTopPosts_FullMethodName        = "/stats.Stats/GetTopPosts"
	Stats_GetTopUsers_FullMethodName        = "/stats.Stats/GetTopUsers"
)

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsClient interface {
	GetPostStat(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostStat, error)
	GetViesDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*ViewsDynamic, error)
	GetLikesDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*LikesDynamic, error)
	GetCommentsDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*CommentsDynamic, error)
	GetTopPosts(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*TopPosts, error)
	GetTopUsers(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*TopUsers, error)
}

type statsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsClient(cc grpc.ClientConnInterface) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetPostStat(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostStat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStat)
	err := c.cc.Invoke(ctx, Stats_GetPostStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetViesDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*ViewsDynamic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewsDynamic)
	err := c.cc.Invoke(ctx, Stats_GetViesDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetLikesDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*LikesDynamic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikesDynamic)
	err := c.cc.Invoke(ctx, Stats_GetLikesDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetCommentsDynamic(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*CommentsDynamic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentsDynamic)
	err := c.cc.Invoke(ctx, Stats_GetCommentsDynamic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetTopPosts(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*TopPosts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopPosts)
	err := c.cc.Invoke(ctx, Stats_GetTopPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetTopUsers(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*TopUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopUsers)
	err := c.cc.Invoke(ctx, Stats_GetTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
// All implementations must embed UnimplementedStatsServer
// for forward compatibility.
type StatsServer interface {
	GetPostStat(context.Context, *PostRequest) (*PostStat, error)
	GetViesDynamic(context.Context, *PostRequest) (*ViewsDynamic, error)
	GetLikesDynamic(context.Context, *PostRequest) (*LikesDynamic, error)
	GetCommentsDynamic(context.Context, *PostRequest) (*CommentsDynamic, error)
	GetTopPosts(context.Context, *Attribute) (*TopPosts, error)
	GetTopUsers(context.Context, *Attribute) (*TopUsers, error)
	mustEmbedUnimplementedStatsServer()
}

// UnimplementedStatsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServer struct{}

func (UnimplementedStatsServer) GetPostStat(context.Context, *PostRequest) (*PostStat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostStat not implemented")
}
func (UnimplementedStatsServer) GetViesDynamic(context.Context, *PostRequest) (*ViewsDynamic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViesDynamic not implemented")
}
func (UnimplementedStatsServer) GetLikesDynamic(context.Context, *PostRequest) (*LikesDynamic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikesDynamic not implemented")
}
func (UnimplementedStatsServer) GetCommentsDynamic(context.Context, *PostRequest) (*CommentsDynamic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsDynamic not implemented")
}
func (UnimplementedStatsServer) GetTopPosts(context.Context, *Attribute) (*TopPosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPosts not implemented")
}
func (UnimplementedStatsServer) GetTopUsers(context.Context, *Attribute) (*TopUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatsServer) mustEmbedUnimplementedStatsServer() {}
func (UnimplementedStatsServer) testEmbeddedByValue()               {}

// UnsafeStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServer will
// result in compilation errors.
type UnsafeStatsServer interface {
	mustEmbedUnimplementedStatsServer()
}

func RegisterStatsServer(s grpc.ServiceRegistrar, srv StatsServer) {
	// If the following call pancis, it indicates UnimplementedStatsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stats_ServiceDesc, srv)
}

func _Stats_GetPostStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetPostStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetPostStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetPostStat(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetViesDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetViesDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetViesDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetViesDynamic(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetLikesDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetLikesDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetLikesDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetLikesDynamic(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetCommentsDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetCommentsDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetCommentsDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetCommentsDynamic(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetTopPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attribute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetTopPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetTopPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetTopPosts(ctx, req.(*Attribute))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attribute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetTopUsers(ctx, req.(*Attribute))
	}
	return interceptor(ctx, in, info, handler)
}

// Stats_ServiceDesc is the grpc.ServiceDesc for Stats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStat",
			Handler:    _Stats_GetPostStat_Handler,
		},
		{
			MethodName: "GetViesDynamic",
			Handler:    _Stats_GetViesDynamic_Handler,
		},
		{
			MethodName: "GetLikesDynamic",
			Handler:    _Stats_GetLikesDynamic_Handler,
		},
		{
			MethodName: "GetCommentsDynamic",
			Handler:    _Stats_GetCommentsDynamic_Handler,
		},
		{
			MethodName: "GetTopPosts",
			Handler:    _Stats_GetTopPosts_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _Stats_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
